```{r}
library(ggplot2)
library(dplyr)
library(psych)
```

```{r}
df <- read.csv("Top100Backers - Top100Backers.csv")
```

```{r}
head(df)
```

```{r}
summary(df)
```

```{r}
describe(df)
```

```{r}
ggplot(df, aes(amount)) + geom_histogram(colour="black", fill= "#f0db4f") +
  geom_vline(aes(xintercept=mean(amount)), colour="black", linetype="dashed", size=1) +
  geom_vline(aes(xintercept=median(amount)), colour='red', linetype="dashed", size=1) +
  theme_bw() +
  ylab("Total Amount") +
  xlab("Count") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))
```

With Samsung. We will remove it but still, the SKEW IS HUGE. 

```{r}
df_sans_samsung <- filter(df, backer != "https://opencollective.com/samsung-next")
```

Because samsung is so big, and they erm, list their own project as the list of many of their contributions. I removed it for this case. 

```{r}
ggplot(df_sans_samsung, aes(amount)) + geom_histogram(colour="black", fill= "#f0db4f") +
  geom_vline(aes(xintercept=mean(amount)), colour="black", linetype="dashed", size=1) +
  geom_vline(aes(xintercept=median(amount)), colour='red', linetype="dashed", size=1) +
  theme_bw() +
  ggtitle("Distribution of Open Source Funding from Top Donors") +
  ylab("Total Amount") +
  xlab("Count") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))
```

```{r}
summary(df_sans_samsung)
```

